version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/honey_hotel_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=honeyhotel123
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: honeyhotel123
      POSTGRES_DB: honey_hotel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
