DROP TABLE IF EXISTS spring_session CASCADE;
DROP TABLE IF EXISTS spring_session_attributes CASCADE;

CREATE TABLE IF NOT EXISTS activities (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2),
    category VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    password_hash VARCHAR(255),
    title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS reservations (
    id SERIAL PRIMARY KEY,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    adults INTEGER NOT NULL DEFAULT 1,
    children INTEGER NOT NULL DEFAULT 0,
    promo_code VARCHAR(50),
    rate_option VARCHAR(50),
    total_price NUMERIC(10, 2),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS roomcategories (
    id SERIAL PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL,
    hotel_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS rooms (
    id SERIAL PRIMARY KEY,
    bed_type VARCHAR(20) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    smoking_allowed BOOLEAN NOT NULL,
    room_type_id INT NOT NULL,
    room_category_id INT NOT NULL,
    price_category VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS roomtypes (
    id SERIAL PRIMARY KEY,
    type_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS activityreservations (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_id INTEGER NOT NULL,
    hotel_reservation_id BIGINT NOT NULL,
    reservation_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (activity_id) REFERENCES activities(id),
    FOREIGN KEY (hotel_reservation_id) REFERENCES reservations(id)
);


CREATE TABLE IF NOT EXISTS promo_codes (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    discount_percentage NUMERIC(5, 2) NOT NULL,
    creation_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS spring_session (
    primary_id CHARACTER(36) PRIMARY KEY,
    session_id CHARACTER(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INT NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS spring_session_attributes (
    session_primary_id CHARACTER(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id) REFERENCES spring_session (primary_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    id SERIAL PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT password_reset_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS password_reset_token_token_idx ON password_reset_token (token);


INSERT INTO activities (name, price, category) VALUES
('Beachside Yoga', 50.00, 'Soothing'),
('Guided Nature Walk', 30.00, 'Interactive'),
('Jet Skiing', 120.00, 'Exciting'),
('Snorkeling', 80.00, 'Exciting'),
('Cultural Excursion', 70.00, 'Interactive'),
('Cooking Class', 60.00, 'Interactive'),
('Spa Treatment', 150.00, 'Soothing'),
('Hiking Trip', 40.00, 'Exciting'),
('Scuba Diving', 200.00, 'Exciting'),
('Paragliding', 250.00, 'Exciting');

INSERT INTO hotels (name) VALUES
('Brazos Bliss Hotel, Waco, Texas, USA'),
('The Grand Palace, Paris, France'),
('Seaside Serenity Resort, Phuket, Thailand'),
('Urban Oasis, Tokyo, Japan'),
('Misty Mountain Lodge, Queenstown, New Zealand'),
('Desert Mirage Hotel, Dubai, UAE'),
('Maple Leaf Lodge, Banff, Canada'),
('Savannah Retreat, Nairobi, Kenya'),
('Alpine Meadows Hotel, Interlaken, Switzerland'),
('Casa Del Sol, Barcelona, Spain'),
('Emerald Bay Resort, Bora Bora, French Polynesia'),
('Crescent Cove Hotel, Sydney, Australia'),
('Royal Garden Inn, London, UK'),
('Blue Lagoon Resort, Reykjavik, Iceland'),
('Rainforest Hideaway, Tulum, Mexico'),
('Golden Sands Hotel, Cape Town, South Africa'),
('Redwood Retreat, San Francisco, California, USA'),
('Lakefront Lodge, Queenstown, New Zealand'),
('Coconut Grove Resort, Bali, Indonesia'),
('Northern Lights Inn, Tromsø, Norway');

INSERT INTO roomcategories (category_name, hotel_id) VALUES
('Nature Retreat', 1),
('Urban Elegance', 1),
('Vintage Charm', 1);

INSERT INTO rooms (bed_type, price, smoking_allowed, room_type_id, room_category_id, price_category) VALUES
('twin', 590.00, true, 1, 1, 'comfort'),
('twin', 590.00, false, 1, 1, 'comfort'),
('full', 590.00, true, 1, 1, 'comfort'),
('full', 590.00, false, 1, 1, 'comfort'),
('queen', 590.00, true, 1, 1, 'comfort'),
('queen', 590.00, false, 1, 1, 'comfort'),
('king', 590.00, true, 1, 1, 'comfort'),
('king', 590.00, false, 1, 1, 'comfort'),
('twin', 1110.00, true, 1, 1, 'business'),
('twin', 1110.00, false, 1, 1, 'business'),
('full', 1110.00, true, 1, 1, 'business'),
('full', 1110.00, false, 1, 1, 'business'),
('queen', 1110.00, true, 1, 1, 'business'),
('queen', 1110.00, false, 1, 1, 'business'),
('twin', 1130.00, true, 1, 1, 'executive'),
('twin', 1130.00, false, 1, 1, 'executive'),
('full', 1130.00, true, 1, 1, 'executive'),
('full', 1130.00, false, 1, 1, 'executive'),
('queen', 1130.00, true, 1, 1, 'executive'),
('queen', 1130.00, false, 1, 1, 'executive'),
('twin', 475.00, true, 1, 1, 'economy'),
('twin', 475.00, false, 1, 1, 'economy'),
('full', 475.00, true, 1, 1, 'economy'),
('full', 475.00, false, 1, 1, 'economy'),
('queen', 475.00, true, 1, 1, 'economy'),
('queen', 475.00, false, 1, 1, 'economy'),
('king', 475.00, true, 1, 1, 'economy'),
('king', 475.00, false, 1, 1, 'economy'),
('king', 1130.00, true, 1, 1, 'executive'),
('king', 1130.00, false, 1, 1, 'executive'),
('twin', 1130.00, true, 2, 1, 'executive'),
('twin', 1130.00, false, 2, 1, 'executive'),
('full', 1130.00, true, 2, 1, 'executive'),
('full', 1130.00, false, 2, 1, 'executive'),
('queen', 1130.00, true, 2, 1, 'executive'),
('queen', 1130.00, false, 2, 1, 'executive'),
('king', 1130.00, true, 2, 1, 'executive'),
('king', 1130.00, false, 2, 1, 'executive'),
('twin', 1130.00, true, 3, 1, 'executive'),
('twin', 1130.00, false, 3, 1, 'executive'),
('full', 1130.00, true, 3, 1, 'executive'),
('full', 1130.00, false, 3, 1, 'executive'),
('queen', 1130.00, true, 3, 1, 'executive'),
('queen', 1130.00, false, 3, 1, 'executive'),
('king', 1130.00, true, 3, 1, 'executive'),
('king', 1130.00, false, 3, 1, 'executive'),
('king', 590.00, false, 1, 1, 'comfort'),
('twin', 590.00, true, 2, 1, 'comfort'),
('twin', 590.00, false, 2, 1, 'comfort'),
('full', 590.00, true, 2, 1, 'comfort'),
('full', 590.00, false, 2, 1, 'comfort'),
('queen', 590.00, true, 2, 1, 'comfort'),
('queen', 590.00, false, 2, 1, 'comfort'),
('king', 590.00, true, 2, 1, 'comfort'),
('king', 590.00, false, 2, 1, 'comfort'),
('twin', 590.00, true, 3, 1, 'comfort'),
('twin', 590.00, false, 3, 1, 'comfort'),
('full', 590.00, true, 3, 1, 'comfort'),
('full', 590.00, false, 3, 1, 'comfort'),
('queen', 590.00, true, 3, 1, 'comfort'),
('queen', 590.00, false, 3, 1, 'comfort'),
('king', 590.00, true, 3, 1, 'comfort'),
('king', 590.00, false, 3, 1, 'comfort'),
('king', 1110.00, true, 1, 1, 'business'),
('king', 1110.00, false, 1, 1, 'business'),
('twin', 1110.00, true, 2, 1, 'business'),
('twin', 1110.00, false, 2, 1, 'business'),
('full', 1110.00, true, 2, 1, 'business'),
('full', 1110.00, false, 2, 1, 'business'),
('queen', 1110.00, true, 2, 1, 'business'),
('queen', 1110.00, false, 2, 1, 'business'),
('king', 1110.00, true, 2, 1, 'business'),
('king', 1110.00, false, 2, 1, 'business'),
('twin', 1110.00, true, 3, 1, 'business'),
('twin', 1110.00, false, 3, 1, 'business'),
('full', 1110.00, true, 3, 1, 'business'),
('full', 1110.00, false, 3, 1, 'business'),
('queen', 1110.00, true, 3, 1, 'business'),
('queen', 1110.00, false, 3, 1, 'business'),
('king', 1110.00, true, 3, 1, 'business'),
('king', 1110.00, false, 3, 1, 'business'),
('twin', 475.00, true, 2, 1, 'economy'),
('twin', 475.00, false, 2, 1, 'economy'),
('full', 475.00, true, 2, 1, 'economy'),
('full', 475.00, false, 2, 1, 'economy'),
('queen', 475.00, true, 2, 1, 'economy'),
('queen', 475.00, false, 2, 1, 'economy'),
('king', 475.00, true, 2, 1, 'economy'),
('king', 475.00, false, 2, 1, 'economy'),
('twin', 475.00, true, 3, 1, 'economy'),
('twin', 475.00, false, 3, 1, 'economy'),
('full', 475.00, true, 3, 1, 'economy'),
('full', 475.00, false, 3, 1, 'economy'),
('queen', 475.00, true, 3, 1, 'economy'),
('queen', 475.00, false, 3, 1, 'economy'),
('king', 475.00, true, 3, 1, 'economy'),
('king', 475.00, false, 3, 1, 'economy'),
('twin', 350.00, true, 4, 2, 'economy'),
('twin', 350.00, false, 4, 2, 'economy'),
('twin', 525.00, true, 4, 2, 'comfort'),
('twin', 525.00, false, 4, 2, 'comfort'),
('twin', 700.00, true, 4, 2, 'business'),
('twin', 700.00, false, 4, 2, 'business'),
('twin', 1050.00, true, 4, 2, 'executive'),
('twin', 1050.00, false, 4, 2, 'executive'),
('full', 400.00, true, 4, 2, 'economy'),
('full', 400.00, false, 4, 2, 'economy'),
('full', 525.00, true, 4, 2, 'comfort'),
('full', 525.00, false, 4, 2, 'comfort'),
('full', 700.00, true, 4, 2, 'business'),
('full', 700.00, false, 4, 2, 'business'),
('full', 1050.00, true, 4, 2, 'executive'),
('full', 1050.00, false, 4, 2, 'executive'),
('queen', 455.00, true, 4, 2, 'economy'),
('queen', 455.00, false, 4, 2, 'economy'),
('queen', 630.00, true, 4, 2, 'comfort'),
('queen', 630.00, false, 4, 2, 'comfort'),
('queen', 805.00, true, 4, 2, 'business'),
('queen', 805.00, false, 4, 2, 'business'),
('queen', 1155.00, true, 4, 2, 'executive'),
('queen', 1155.00, false, 4, 2, 'executive'),
('king', 490.00, true, 4, 2, 'economy'),
('king', 490.00, false, 4, 2, 'economy'),
('king', 665.00, true, 4, 2, 'comfort'),
('king', 665.00, false, 4, 2, 'comfort'),
('king', 840.00, true, 4, 2, 'business'),
('king', 840.00, false, 4, 2, 'business'),
('king', 1190.00, true, 4, 2, 'executive'),
('king', 1190.00, false, 4, 2, 'executive'),
('twin', 385.00, true, 5, 2, 'economy'),
('twin', 385.00, false, 5, 2, 'economy'),
('twin', 560.00, true, 5, 2, 'comfort'),
('twin', 560.00, false, 5, 2, 'comfort'),
('twin', 735.00, true, 5, 2, 'business'),
('twin', 735.00, false, 5, 2, 'business'),
('twin', 1085.00, true, 5, 2, 'executive'),
('twin', 1085.00, false, 5, 2, 'executive'),
('full', 455.00, true, 5, 2, 'economy'),
('full', 455.00, false, 5, 2, 'economy'),
('full', 630.00, true, 5, 2, 'comfort'),
('full', 630.00, false, 5, 2, 'comfort'),
('full', 805.00, true, 5, 2, 'business'),
('full', 805.00, false, 5, 2, 'business'),
('full', 1155.00, true, 5, 2, 'executive'),
('full', 1155.00, false, 5, 2, 'executive'),
('queen', 490.00, true, 5, 2, 'economy'),
('queen', 490.00, false, 5, 2, 'economy'),
('queen', 665.00, true, 5, 2, 'comfort'),
('queen', 665.00, false, 5, 2, 'comfort'),
('queen', 840.00, true, 5, 2, 'business'),
('queen', 840.00, false, 5, 2, 'business'),
('queen', 1190.00, true, 5, 2, 'executive'),
('queen', 1190.00, false, 5, 2, 'executive'),
('king', 525.00, true, 5, 2, 'economy'),
('king', 525.00, false, 5, 2, 'economy'),
('king', 700.00, true, 5, 2, 'comfort'),
('king', 700.00, false, 5, 2, 'comfort'),
('king', 875.00, true, 5, 2, 'business'),
('king', 875.00, false, 5, 2, 'business'),
('king', 1225.00, true, 5, 2, 'executive'),
('king', 1225.00, false, 5, 2, 'executive'),
('twin', 350.00, true, 6, 3, 'economy'),
('twin', 350.00, false, 6, 3, 'economy'),
('twin', 525.00, true, 6, 3, 'comfort'),
('twin', 525.00, false, 6, 3, 'comfort'),
('twin', 700.00, true, 6, 3, 'business'),
('twin', 700.00, false, 6, 3, 'business'),
('twin', 1050.00, true, 6, 3, 'executive'),
('twin', 1050.00, false, 6, 3, 'executive'),
('full', 400.00, true, 6, 3, 'economy'),
('full', 400.00, false, 6, 3, 'economy'),
('full', 525.00, true, 6, 3, 'comfort'),
('full', 525.00, false, 6, 3, 'comfort'),
('full', 700.00, true, 6, 3, 'business'),
('full', 700.00, false, 6, 3, 'business'),
('full', 1050.00, true, 6, 3, 'executive'),
('full', 1050.00, false, 6, 3, 'executive'),
('queen', 455.00, true, 6, 3, 'economy'),
('queen', 455.00, false, 6, 3, 'economy'),
('queen', 630.00, true, 6, 3, 'comfort'),
('queen', 630.00, false, 6, 3, 'comfort'),
('queen', 805.00, true, 6, 3, 'business'),
('queen', 805.00, false, 6, 3, 'business'),
('queen', 1155.00, true, 6, 3, 'executive'),
('queen', 1155.00, false, 6, 3, 'executive'),
('king', 490.00, true, 6, 3, 'economy'),
('king', 490.00, false, 6, 3, 'economy'),
('king', 665.00, true, 6, 3, 'comfort'),
('king', 665.00, false, 6, 3, 'comfort'),
('king', 840.00, true, 6, 3, 'business'),
('king', 840.00, false, 6, 3, 'business'),
('king', 1190.00, true, 6, 3, 'executive'),
('king', 1190.00, false, 6, 3, 'executive'),
('twin', 370.00, true, 5, 3, 'economy'),
('twin', 370.00, false, 5, 3, 'economy'),
('twin', 545.00, true, 5, 3, 'comfort'),
('twin', 545.00, false, 5, 3, 'comfort'),
('twin', 720.00, true, 5, 3, 'business'),
('twin', 720.00, false, 5, 3, 'business'),
('twin', 1070.00, true, 5, 3, 'executive'),
('twin', 1070.00, false, 5, 3, 'executive'),
('full', 420.00, true, 5, 3, 'economy'),
('full', 420.00, false, 5, 3, 'economy'),
('full', 545.00, true, 5, 3, 'comfort'),
('full', 545.00, false, 5, 3, 'comfort'),
('full', 720.00, true, 5, 3, 'business'),
('full', 720.00, false, 5, 3, 'business'),
('full', 1070.00, true, 5, 3, 'executive'),
('full', 1070.00, false, 5, 3, 'executive'),
('queen', 455.00, true, 5, 3, 'economy'),
('queen', 455.00, false, 5, 3, 'economy'),
('queen', 630.00, true, 5, 3, 'comfort'),
('queen', 630.00, false, 5, 3, 'comfort'),
('queen', 805.00, true, 5, 3, 'business'),
('queen', 805.00, false, 5, 3, 'business'),
('queen', 1155.00, true, 5, 3, 'executive'),
('queen', 1155.00, false, 5, 3, 'executive'),
('king', 490.00, true, 5, 3, 'economy'),
('king', 490.00, false, 5, 3, 'economy'),
('king', 665.00, true, 5, 3, 'comfort'),
('king', 665.00, false, 5, 3, 'comfort'),
('king', 840.00, true, 5, 3, 'business'),
('king', 840.00, false, 5, 3, 'business'),
('king', 1190.00, true, 5, 3, 'executive'),
('king', 1190.00, false, 5, 3, 'executive');

-- Initialize roomtypes table
INSERT INTO roomtypes (id, type_name) VALUES
(1, 'Single'),
(2, 'Double'),
(3, 'Family'),
(4, 'Suite'),
(5, 'Deluxe'),
(6, 'Standard');

-- Insert initial data into 'users'
INSERT INTO users (email, firstname, lastname, password_hash, title) VALUES
('honeyhotel@gmail.com', 'Honey', 'Hotel', 'ca18b07032cb2ff53855bf1d73fe4f3ac6d71f78b207ec9fc4be8b5ad25b6ee4', NULL);

-- Insert initial data into 'promo_codes'
INSERT INTO promo_codes (name, discount_percentage, creation_date, expiration_date, is_active) VALUES
('ERNESTO50', 50.00, '2024-10-30', '2026-12-31', TRUE);