package com.honey_hotel.backend.model;

import jakarta.persistence.*;

/**
 Main Activities class with functionalities
 @author Samuel Choi
 @version 1.0 (Oct 18 2024)
 */
@Entity
@Table(name = "activities")
public class Activities {

    /**
     * Unique identifier of the activity automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Non-null activity name
     */
    @Column(nullable = false)
    private String name;

    /**
     * Non-null activity price
     */
    @Column(nullable = false)
    private double price;

    /**
     * Non-null category name
     */
    @Column(nullable = false)
    private String category;

<<<<<<< HEAD
    // Getters and Setters
    /**
     * Gets the unique identifier of the activity
     *
     * @return Activity ID
     */
=======
>>>>>>> 61dad834af4f6f2b9fb693043a903f313e256c90
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the activity
     *
     * @param id activity ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the activity
     *
     * @return Activity name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the activity
     *
     * @param name activity name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the price of the activity
     *
     * @return Activity price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the price of the activity
     *
     * @param price activity price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Gets the category of the activity
     *
     * @return Activity category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the category of the activity
     *
     * @param category Activity category
     */
    public void setCategory(String category) {
        this.category = category;
    }
}
