package com.honey_hotel.backend.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 Main Hotel class with functionalities
 @author Samuel Choi
 @version 1.0 (Oct 11 2024)
 */
@Entity
@Table(name = "hotels")
public class Hotel {

    /**
     * Unique identifier of the activity automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Hotel name
     */
    private String name;

    /**
     * List of room categories associated with the hotel
     * Each category contains different types of rooms available in the hotel
     */
    @OneToMany(mappedBy = "hotel", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<RoomCategory> roomCategories;

    // Getters and setters
    /**
     * Gets the unique identifier of the hotel
     *
     * @return hotel ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the hotel
     *
     * @param id hotel ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the hotel
     *
     * @return hotel name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the hotel
     *
     * @param name hotel name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the list of room categories associated with the hotel
     *
     * @return list of room categories
     */
    public List<RoomCategory> getRoomCategories() {
        return roomCategories;
    }

    /**
     * Sets the list of room categories associated with the hotel
     *
     * @param roomCategories list of room categories to set
     */
    public void setRoomCategories(List<RoomCategory> roomCategories) {
        this.roomCategories = roomCategories;
    }
}
