package com.honey_hotel.backend.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/**
 Main Reservation class with functionalities
 @author Samuel Choi
 @version 2.0 (Oct 26 2024)
 */
@Entity
@Table(name = "reservations")
public class Reservation {

    /**
     * Unique identifier of the activity automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Check-in date of the reservation
     */
    @Column(name = "check_in_date", nullable = false)
    private LocalDate checkInDate;

    /**
     * Check-out date of the reservation
     */
    @Column(name = "check_out_date", nullable = false)
    private LocalDate checkOutDate;

    /**
     * The room associated with the reservation
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /**
     * The user who made the reservation
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private AppUser user;

    // Getters and setters
    /**
     * Gets the unique identifier of the reservation
     *
     * @return reservation ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the reservation
     *
     * @param id reservation ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the check-in date of the reservation
     *
     * @return check-in date
     */
    public LocalDate getCheckInDate() {
        return checkInDate;
    }

    /**
     * Sets the check-in date of the reservation
     *
     * @param checkInDate check-in date to set
     */
    public void setCheckInDate(LocalDate checkInDate) {
        this.checkInDate = checkInDate;
    }

    /**
     * Gets the check-out date of the reservation
     *
     * @return check-out date
     */
    public LocalDate getCheckOutDate() {
        return checkOutDate;
    }

    /**
     * Sets the check-out date of the reservation
     *
     * @param checkOutDate check-out date to set
     */
    public void setCheckOutDate(LocalDate checkOutDate) {
        this.checkOutDate = checkOutDate;
    }

    /**
     * Gets the room associated with the reservation
     *
     * @return reservation room
     */
    public Room getRoom() {
        return room;
    }

    /**
     * Sets the room for the reservation
     *
     * @param room reservation room
     */
    public void setRoom(Room room) {
        this.room = room;
    }

    /**
     * Gets the user who made the reservation
     *
     * @return user who made the reservation
     */
    public AppUser getUser() {
        return user;
    }

    /**
     * Sets the user for the reservation
     *
     * @param user user to associate with the reservation
     */
    public void setUser(AppUser user) {
        this.user = user;
    }
}
