package com.honey_hotel.backend.model;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 Main Reservation class with functionalities
 @author Samuel Choi
 @version 2.0 (Oct 26 2024)
 */
@Entity
@Table(name = "reservations")
public class Reservation {

    /**
     * Unique identifier of the activity automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Check-in date of the reservation
     */
    @Column(name = "check_in_date", nullable = false)
    private LocalDate checkInDate;

    /**
     * Check-out date of the reservation
     */
    @Column(name = "check_out_date", nullable = false)
    private LocalDate checkOutDate;

    /**
     * The room associated with the reservation
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /**
     * The user who made the reservation
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private AppUser user;

    // Getters and setters
    /**
     * Gets the unique identifier of the reservation
     *
     * @return reservation ID
     */
    
    @Column(name = "adults", nullable = false)
    private int adults;

    @Column(name = "children", nullable = false)
    private int children;

    @Column(name = "promo_code")
    private String promoCode;

    @Column(name = "rate_option")
    private String rateOption;

    @Column(name = "total_price", precision = 10, scale = 2)
    private BigDecimal totalPrice;

    @Column(name = "room_price", precision = 10, scale = 2)
    private BigDecimal roomPrice;

    @Column(name = "booking_id")
    private String bookingId;

    @Column(name = "chosen_photo_path")
    private String photo_path;

    @Column(name = "hotel_location")
    private String hotelLocation;

    @Column(name = "checked_in")
    private boolean checkedIn;

    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the reservation
     *
     * @param id reservation ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the check-in date of the reservation
     *
     * @return check-in date
     */
    public LocalDate getCheckInDate() {
        return checkInDate;
    }

    /**
     * Sets the check-in date of the reservation
     *
     * @param checkInDate check-in date to set
     */
    public void setCheckInDate(LocalDate checkInDate) {
        this.checkInDate = checkInDate;
    }

    /**
     * Gets the check-out date of the reservation
     *
     * @return check-out date
     */
    public LocalDate getCheckOutDate() {
        return checkOutDate;
    }

    /**
     * Sets the check-out date of the reservation
     *
     * @param checkOutDate check-out date to set
     */
    public void setCheckOutDate(LocalDate checkOutDate) {
        this.checkOutDate = checkOutDate;
    }

    /**
     * Gets the room associated with the reservation
     *
     * @return reservation room
     */
    public Room getRoom() {
        return room;
    }

    /**
     * Sets the room for the reservation
     *
     * @param room reservation room
     */
    public void setRoom(Room room) {
        this.room = room;
    }

    /**
     * Gets the user who made the reservation
     *
     * @return user who made the reservation
     */
    public AppUser getUser() {
        return user;
    }

    /**
     * Sets the user for the reservation
     *
     * @param user user to associate with the reservation
     */
    public void setUser(AppUser user) {
        this.user = user;
    }

    public int getAdults() {
        return adults;
    }

    public void setAdults(int adults) {
        this.adults = adults;
    }

    public int getChildren() {
        return children;
    }

    public void setChildren(int children) {
        this.children = children;
    }

    public String getPromoCode() {
        return promoCode;
    }

    public void setPromoCode(String promoCode) {
        this.promoCode = promoCode;
    }

    public String getRateOption() {
        return rateOption;
    }

    public void setRateOption(String rateOption) {
        this.rateOption = rateOption;
    }

    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    public BigDecimal getRoomPrice() {
        return roomPrice;
    }

    public void setRoomPrice(BigDecimal roomPrice) {
        this.roomPrice = roomPrice;
    }

    public String getBookingId() {
        return bookingId;
    }

    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }

    public String getPhoto_path() {
        return photo_path;
    }

    public void setPhoto_path(String photo_path) {
        this.photo_path = photo_path;
    }

    public String getHotelLocation() {
        return hotelLocation;
    }

    public void setHotelLocation(String hotelLocation) {
        this.hotelLocation = hotelLocation;
    }

    public boolean isCheckedIn() {
        return checkedIn;
    }

    public void setCheckedIn(boolean checkedIn) {
        this.checkedIn = checkedIn;
    }
}
