package com.honey_hotel.backend.model;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 Main Room class with functionalities
 @author Samuel Choi
 @version 3.1 (Oct 18 2024)
 */
@Entity
@Table(name = "rooms")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Room {

    /**
     * Unique identifier of the activity automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The category to which the room belongs (e.g., Nature Retreat, Ocean View)
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "room_category_id", nullable = false)
    @JsonIgnoreProperties("rooms")
    private RoomCategory category;

    /**
     * The bed type in the room (e.g., Single, Double)
     */
    private String bedType;

    /**
     * Indicates whether smoking is allowed in the room
     */
    private boolean smokingAllowed;

    /**
     * Room price
     */
    private double price;


    /**
     * The price category of the room (e.g., economy, comfort)
     */
    @Column(name = "price_category")
    private String priceCategory;

    /**
     * The room type ID, representing the specific type of room (e.g., Single, Double)
     */
    @Column(name = "room_type_id", nullable = false)
    private int roomTypeId;


    /**
     * A static array of room type names mapped to room type IDs
     */
    private static final String[] ROOM_TYPE_NAMES = {
            "Single",
            "Double",
            "Family",
            "Suite",
            "Deluxe",
            "Standard"
    };

    /////// room id
    /**
     * Gets the room ID
     *
     * @return room ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the room type ID
     *
     * @param id room ID
     */
    public void setId(Long id) {
        this.id = id;
    }
    /////// room id

    /////// room category (Nature Retreat, etc.)
    /**
     * Gets the room category
     *
     * @return room category
     */
    public RoomCategory getCategory() {
        return category;
    }

    /**
     * Sets the room category
     *
     * @param category room category
     */
    public void setCategory(RoomCategory category) {
        this.category = category;
    }
    /////// room category (Nature Retreat, etc.)

    /////// bed type (Single, Double, etc.)
    /**
     * Gets the room bed type
     *
     * @return room bed type
     */
    public String getBedType() {
        return bedType;
    }

    /**
     * Sets the room bed type
     *
     * @param bedType room bed type
     */
    public void setBedType(String bedType) {
        this.bedType = bedType;
    }
    /////// bed type (Single, Double, etc.)

    /////// smoking allowed
    /**
     * Gets if room allows smoking
     *
     * @return true if smoking is allowed, false otherwise
     */
    public boolean isSmokingAllowed() {
        return smokingAllowed;
    }

    /**
     * Sets if room allows smoking
     *
     * @param smokingAllowed boolean of if smoking is allowed
     */
    public void setSmokingAllowed(boolean smokingAllowed) {
        this.smokingAllowed = smokingAllowed;
    }
    /////// smoking allowed

    /////// price
    /**
     * Gets room price
     *
     * @return room price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets room price
     *
     * @param price room price
     */
    public void setPrice(double price) {
        this.price = price;
    }
    /////// price

    /**
     * Gets the room type name corresponding to the room type ID
     *
     * @return room type name (e.g., Single, Double, Suite)
     */
    public String getRoomType() {
        if (roomTypeId >= 1 && roomTypeId <= ROOM_TYPE_NAMES.length) {
            return ROOM_TYPE_NAMES[roomTypeId - 1]; // Mapping ID to String
        } else {
            return "Unknown"; // Default if roomTypeId is out of bounds
        }
    }

    /**
     * Gets the room type ID
     *
     * @return room type ID
     */
    public int getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * Sets the room type ID
     *
     * @param roomTypeId room type ID
     */
    public void setRoomTypeId(int roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /////// price category (economy, comfort, etc.)
    /**
     * Gets the room price category (economy, comfort, etc.)
     *
     * @return room price category
     */
    public String getPriceCategory() {
        return priceCategory;
    }

    /**
     * Sets the room price category (economy, comfort, etc.)
     *
     * @param priceCategory room price category
     */
    public void setPriceCategory(String priceCategory) {
        this.priceCategory = priceCategory;
    }
    /////// price category (economy, comfort, etc.)
}
